### PR TITLE
fix(ruff)

### LINKED ISSUE #4815: ❌ build issues: astral.sh/ruff=0.1.12
Running log of build failure for astral.sh/ruff=0.1.12

### LINKED ISSUE #4816: ❌ build issues: github.com/charliermarsh/ruff=0.1.12
Running log of build failure for github.com/charliermarsh/ruff=0.1.12

### PR DESCRIPTION
**Pull request by jhheider**
closes #4815
closes #4816

### CODE REVIEW

File: projects/astral.sh/ruff/package.yml [hunk 1]
```diff
@@ -22,6 +22,8 @@ provides:
 
 test:
   script:
+    - run: mkdir -p .ruff_cache/{{version}}
```
Comment (mxcl) [inline projects/astral.sh/ruff/package.yml:25]: needs comment
